// Centralized icon imports for better tree-shaking
export {
  Plus,
  Search,
  Star,
  Edit,
  Trash2,
  Package,
  Briefcase as Suitcase,
  Check,
  X,
  Home,
  Shirt,
  CheckSquare,
  Settings,
  Sun,
  Moon,
  Download,
  Upload,
  Filter,
  Calendar,
  MapPin,
  Clock,
  MoreVertical,
  RefreshCcw,
  CheckCircle2,
  Luggage,
  Sparkles,
  Lightbulb,
  Target,
  Smartphone,
  Camera,
  FolderOpen,
  Users,
  Zap,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  Briefcase,
  TrendingUp,
  CheckCircle,
  Plus as AddIcon,
  Star as StarIcon,
  Briefcase as BriefcaseIcon,
  CheckSquare as CheckSquareIcon,
  Settings as SettingsIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Filter as FilterIcon,
  Calendar as CalendarIcon,
  MapPin as MapPinIcon,
  Clock as ClockIcon,
  MoreVertical as MoreVerticalIcon,
  RefreshCcw as RefreshCcwIcon,
  CheckCircle2 as CheckCircle2Icon,
  Luggage as LuggageIcon,
  Sparkles as SparklesIcon,
  Lightbulb as LightbulbIcon,
  Target as TargetIcon,
  Smartphone as SmartphoneIcon,
  Camera as CameraIcon,
  FolderOpen as FolderOpenIcon,
  Users as UsersIcon,
  Zap as ZapIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ArrowRight as ArrowRightIcon,
} from 'lucide-react';
